export const eventsMockData = [
    {
        id: 1,
        title: 'Montreal International Jazz Festival',
        category: 'Featured',
        date: '2026-06-25T19:00:00',
        location: 'Place des Arts, Montreal',
        organization: 'Evenko',
        description: 'Experience the world\'s largest jazz festival, featuring legendary artists and rising stars in the heart of downtown Montreal.',
        imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2070&auto=format&fit=crop',
        price: 55,
    },
    {
        id: 2,
        title: 'Indie Music Festival',
        category: 'Music',
        date: '2025-11-12T18:00:00',
        location: 'Parc Jean-Drapeau, Montreal',
        organization: 'Osheaga',
        description: 'A two-day festival showcasing the best up-and-coming indie bands from across the country.',
        imageUrl: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?q=80&w=2070&auto=format&fit=crop',
        price: 75,
    },
    {
        id: 3,
        title: 'Startup Pitch Night',
        category: 'Business',
        date: '2025-11-05T19:00:00',
        location: 'Innovation Hub, Montreal',
        organization: 'Startup Montreal',
        description: 'Watch the city\'s brightest entrepreneurs pitch their ideas to a panel of venture capitalists.',
        imageUrl: 'https://images.unsplash.com/photo-1560439514-4e9645039924?q=80&w=2070&auto=format&fit=crop',
        price: 15,
    },
    {
        id: 4,
        title: 'Advanced React Workshop',
        category: 'Technology',
        date: '2025-11-18T10:00:00',
        location: 'Online',
        organization: 'Concordia Continuing Education',
        description: 'Deep dive into advanced React patterns, hooks, and performance optimization techniques.',
        imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop',
        price: 250,
    },
    {
        id: 5,
        title: 'City Marathon 2025',
        category: 'Sports',
        date: '2025-10-19T07:00:00',
        location: 'Mount Royal Park, Montreal',
        organization: 'Run Montreal',
        description: 'Join thousands of runners in the annual city marathon. All skill levels welcome.',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=2070&auto=format&fit=crop',
        price: 40,
    },
    {
        id: 6,
        title: 'Artisan Market Fair',
        category: 'Community',
        date: '2025-10-26T11:00:00',
        location: 'Old Port, Montreal',
        organization: 'City of Montreal',
        description: 'Discover unique handmade crafts, local food, and live music at our weekend market.',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2070&auto=format&fit=crop',
        price: 'Free',
    },
    {
        id: 7,
        title: 'Annual Tech Summit 2025',
        category: 'Featured',
        date: '2025-10-25T09:00:00',
        location: 'Convention Center, Montreal',
        organization: 'Tech Summit Inc.',
        description: 'Join industry leaders to discuss the future of technology, from AI to quantum computing.',
        imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=2070&auto=format&fit=crop',
        price: 499,
    },
    {
        id: 8,
        title: 'Cinephile\'s Dream: Film Noir Retrospective',
        category: 'Arts & Culture',
        date: '2025-11-20T19:00:00',
        location: 'Cinéma du Parc, Montreal',
        organization: 'Cinéma du Parc',
        description: 'A month-long retrospective celebrating the dark and stylish world of classic film noir.',
        imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963e?q=80&w=2070&auto=format&fit=crop',
        price: 12,
    },
    {
        id: 9,
        title: 'Oktoberfest Montreal',
        category: 'Food & Drink',
        date: '2025-10-11T14:00:00',
        location: 'Lachine Canal, Montreal',
        organization: 'Les Amis du Canal',
        description: 'Enjoy a taste of Bavaria with craft beer, traditional food, and live oompah bands.',
        imageUrl: 'https://images.unsplash.com/photo-1598801269323-315159d84f83?q=80&w=2070&auto=format&fit=crop',
        price: 20,
    },
    {
        id: 10,
        title: 'Digital Marketing Conference',
        category: 'Education',
        date: '2025-11-22T09:00:00',
        location: 'Palais des congrès, Montreal',
        organization: 'Marketing Pro',
        description: 'Learn the latest trends in SEO, social media, and content marketing from industry experts.',
        imageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=2070&auto=format&fit=crop',
        price: 150,
    },
    {
        id: 11,
        title: 'Yoga & Mindfulness Retreat',
        category: 'Health & Wellness',
        date: '2025-12-06T10:00:00',
        location: 'Eastern Townships, QC',
        organization: 'ZenSpace Retreats',
        description: 'A full-day retreat to de-stress before exams. Includes guided meditation and yoga sessions.',
        imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=2120&auto=format&fit=crop',
        price: 120,
    },
    {
        id: 12,
        title: 'Holiday Baking Masterclass',
        category: 'Food & Drink',
        date: '2025-12-13T13:00:00',
        location: 'Ateliers & Saveurs, Montreal',
        organization: 'Ateliers & Saveurs',
        description: 'Learn how to create delicious holiday treats from a professional pastry chef.',
        imageUrl: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?q=80&w=1964&auto=format&fit=crop',
        price: 85,
    },
    {
        id: 13,
        title: 'Community Volunteer Day',
        category: 'Community',
        date: '2025-11-30T10:00:00',
        location: 'Multiple Locations, Montreal',
        organization: 'Je Vois Mtl',
        description: 'Join us in giving back to the community. Choose from various projects across the city.',
        imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?q=80&w=2070&auto=format&fit=crop',
        price: 'Free',
    },
    {
        id: 14,
        title: 'Charity Soccer Tournament',
        category: 'Sports',
        date: '2025-11-15T09:00:00',
        location: 'Concordia Stadium, Montreal',
        organization: 'Concordia Athletics',
        description: 'Form a team and compete for a good cause. All proceeds go to local youth sports programs.',
        imageUrl: 'https://images.unsplash.com/photo-1552667466-07770ae110d0?q=80&w=2070&auto=format&fit=crop',
        price: 10,
    },
    {
        id: 15,
        title: 'Networking for Young Professionals',
        category: 'Business',
        date: '2025-11-28T18:30:00',
        location: 'Downtown Rooftop Bar, Montreal',
        organization: 'Young Professionals MTL',
        description: 'Expand your professional network in a relaxed and friendly atmosphere. Light appetizers provided.',
        imageUrl: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?q=80&w=2070&auto=format&fit=crop',
        price: 25,
    },
    {
        id: 16,
        title: 'Modern Art Exhibition Opening',
        category: 'Featured',
        date: '2025-12-05T19:00:00',
        location: 'Galerie d\'Art Contemporain, Montreal',
        organization: 'Art Contemporain Mtl',
        description: 'Be the first to see the new collection from groundbreaking international and local artists.',
        imageUrl: 'https://images.unsplash.com/photo-1506806732259-39c2d0268443?q=80&w=2070&auto=format&fit=crop',
        price: 'Free',
    },
    {
        id: 17,
        title: 'The Ethics of AI: A Public Debate',
        category: 'Technology',
        date: '2025-11-26T18:00:00',
        location: 'McGill University, Leacock 132',
        organization: 'McGill University',
        description: 'Leading experts debate the moral and ethical implications of artificial intelligence in our society.',
        imageUrl: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?q=80&w=2070&auto=format&fit=crop',
        price: 'Free',
    },
    {
        id: 18,
        title: 'Public Speaking Workshop',
        category: 'Education',
        date: '2025-12-02T13:00:00',
        location: 'Concordia University, Webster Library',
        organization: 'Concordia University',
        description: 'Conquer your fear of public speaking and learn to deliver presentations with confidence.',
        imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=1974&auto=format&fit=crop',
        price: 50,
    }
];

export const generateRandomTicketNumber = (length = 15) => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';

    for (let i = 0; i < length; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }

    return result;
}
